"""Schema for the per-model system-voice catalog, ``models/<adapter_id>/voices.yaml``.

The catalog is the data behind ``list_voice_profiles`` and the TTS adapters' local voice
check. It is generated by ``scripts/migrate_voice_catalogs.py`` from the platform's
``model_audio_voices`` export, which is the source of truth: regenerate, don't hand-edit. Every selection fact is an explicit field
rather than something inferred from provider wording: ``gender`` used to be guessed by
matching words like ``female`` in ids and labels, which tagged almost none of MiniMax's
English-named voices (``Japanese_KindLady``), and ``language`` was a substring match
over each card's own spelling, so ``English`` matched neither ``英文`` nor ``美式英语``.

Shape::

    schema_version: 1
    source: "where the list came from"      # optional provenance
    voices:
      - voice: "Japanese_KindLady"          # the generate_audio.voice value, verbatim
        label: "Kind Lady"                  # display only, never a valid voice value
        languages: [ja]                     # codes from capabilities/voice_languages.yaml
        gender: female                      # male | female | neutral | unknown
        age: young                          # optional: child | young | middle_aged | senior
        accent: "中国台湾口音"                # optional; only what `languages` cannot say
        description: "…"                    # optional prose about timbre and fit
        tags: [温柔妩媚, 有声书与小说]          # optional free-form selection tags
        default: true                       # optional; at most one per file

``voice`` is an opaque provider handle and is never stripped or normalised: some MiniMax
ids legitimately contain full-width brackets or irregular casing, and "tidying" one is
upstream error 2054. Write it double-quoted in YAML.

``gender`` is required and has no null: ``neutral`` is for non-human voices (robots,
animals), and ``unknown`` is an explicit "nobody has listened to this one yet" — a
voice marked ``unknown`` is still listed, but never returned by a gender filter, since
putting it on either side would be a guess presented as a fact.

**Inheritance.** A model directory without its own ``voices.yaml`` uses the nearest
ancestor's through its ``adapter.yaml`` ``extends`` chain (MiniMax Turbo reads HD's). A
file replaces the ancestor's catalog wholesale; there is no per-voice merge.
"""

from __future__ import annotations

import re
from functools import lru_cache
from pathlib import Path
from typing import Any, Literal, Optional

import yaml
from pydantic import BaseModel, ConfigDict, Field, ValidationInfo, field_validator, model_validator

LANGUAGES_PATH = Path(__file__).parent / "capabilities" / "voice_languages.yaml"
MODELS_DIR = Path(__file__).parent / "models"
VOICES_FILENAME = "voices.yaml"

Gender = Literal["male", "female", "neutral", "unknown"]
#: The genders a caller may filter by; ``unknown`` is a review state, not a choice.
FILTERABLE_GENDERS = ("male", "female", "neutral")
AgeGroup = Literal["child", "young", "middle_aged", "senior"]
AGE_GROUPS = ("child", "young", "middle_aged", "senior")

_LANGUAGE_CODE = re.compile(r"^[a-z]{2,3}(-[A-Za-z0-9]+)*$")


class LanguageEntry(BaseModel):
    model_config = ConfigDict(extra="forbid")

    name: str = Field(min_length=1)
    aliases: list[str] = Field(default_factory=list)


class LanguageVocabulary(BaseModel):
    """The closed set of language codes a voice may declare, plus how callers spell them."""

    model_config = ConfigDict(extra="forbid")

    schema_version: Literal[1]
    languages: dict[str, LanguageEntry] = Field(min_length=1)

    @model_validator(mode="after")
    def _check_codes_and_aliases(self) -> "LanguageVocabulary":
        owner: dict[str, str] = {}
        for code, entry in self.languages.items():
            if not _LANGUAGE_CODE.match(code):
                raise ValueError(f"language code {code!r} is not BCP 47-style")
            for spelling in (code, entry.name, *entry.aliases):
                key = spelling.casefold().strip()
                if owner.setdefault(key, code) != code:
                    raise ValueError(
                        f"language spelling {spelling!r} is claimed by both "
                        f"{owner[key]!r} and {code!r}"
                    )
        return self

    def resolve(self, text: str) -> Optional[str]:
        """Map a caller's spelling (code, name, or alias; case-insensitive) to a code."""
        key = text.casefold().strip()
        for code, entry in self.languages.items():
            if key in {s.casefold().strip() for s in (code, entry.name, *entry.aliases)}:
                return code
        return None


def language_matches(voice_languages: list[str], requested: str) -> bool:
    """Subtag-prefix match: ``en`` covers ``en-US``; ``zh`` covers ``zh-sichuan`` but not ``yue``."""
    return any(code == requested or code.startswith(requested + "-") for code in voice_languages)


@lru_cache(maxsize=None)
def load_language_vocabulary(path: Path = LANGUAGES_PATH) -> LanguageVocabulary:
    return LanguageVocabulary.model_validate(yaml.safe_load(path.read_text(encoding="utf-8")))


class VoiceEntry(BaseModel):
    model_config = ConfigDict(extra="forbid")

    voice: str = Field(min_length=1)
    label: str = Field(min_length=1)
    languages: list[str] = Field(min_length=1)
    gender: Gender
    age: Optional[AgeGroup] = None
    accent: Optional[str] = Field(default=None, min_length=1)
    description: Optional[str] = Field(default=None, min_length=1)
    tags: list[str] = Field(default_factory=list)
    default: bool = False

    @field_validator("voice")
    @classmethod
    def _voice_not_blank(cls, v: str) -> str:
        # Checked, never stripped: the handle is returned byte-for-byte.
        if not v.strip():
            raise ValueError("voice must not be blank")
        return v

    @field_validator("languages", "tags")
    @classmethod
    def _unique_non_empty(cls, v: list[str]) -> list[str]:
        if any(not item.strip() for item in v):
            raise ValueError("entries must not be blank")
        if len(v) != len(set(v)):
            raise ValueError(f"duplicate entries in {v}")
        return v


class VoiceCatalog(BaseModel):
    model_config = ConfigDict(extra="forbid")

    schema_version: Literal[1]
    source: Optional[str] = None
    voices: list[VoiceEntry] = Field(min_length=1)

    @model_validator(mode="after")
    def _check_catalog(self, info: ValidationInfo) -> "VoiceCatalog":
        ids = [v.voice for v in self.voices]
        duplicates = sorted({voice for voice in ids if ids.count(voice) > 1})
        if duplicates:
            raise ValueError(f"duplicate voice ids: {duplicates}")

        defaults = [v.voice for v in self.voices if v.default]
        if len(defaults) > 1:
            raise ValueError(f"at most one default voice, got {defaults}")

        context = info.context or {}
        vocabulary: LanguageVocabulary = context.get("languages") or load_language_vocabulary()
        unknown = sorted(
            {code for v in self.voices for code in v.languages} - set(vocabulary.languages)
        )
        if unknown:
            raise ValueError(f"language codes not in voice_languages.yaml: {unknown}")
        return self


def load_voice_catalog(path: Path, vocabulary: LanguageVocabulary | None = None) -> VoiceCatalog:
    raw: Any = yaml.safe_load(path.read_text(encoding="utf-8"))
    return VoiceCatalog.model_validate(raw, context={"languages": vocabulary})


def catalog_path(adapter_id: str, models_dir: Path = MODELS_DIR) -> Optional[Path]:
    """The ``voices.yaml`` serving ``adapter_id``: its own, else the nearest ``extends`` ancestor's.

    Walks the raw ``adapter.yaml`` files rather than the registry, so a variant still
    finds its catalog when the parent model is disabled in config.yaml.
    """
    seen: set[str] = set()
    current: Optional[str] = adapter_id
    while current and current not in seen:
        seen.add(current)
        path = models_dir / current / VOICES_FILENAME
        if path.exists():
            return path
        adapter_yaml = models_dir / current / "adapter.yaml"
        if not adapter_yaml.exists():
            return None
        current = (yaml.safe_load(adapter_yaml.read_text(encoding="utf-8")) or {}).get("extends")
    return None


@lru_cache(maxsize=None)
def catalog_for_adapter(adapter_id: str) -> Optional[VoiceCatalog]:
    """The validated catalog for a model, or None for a model with no system-voice list.

    Cached: catalogs ship inside the package and never change at runtime.
    """
    path = catalog_path(adapter_id)
    return load_voice_catalog(path) if path else None
